version: '3.8'

services:
  app:
    build:
      context: docker
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - 3306:3306
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
